print("A Gift Of a Friend – Demi Lovato")
print("A Thousand Years – Christina Perri")
print("Apologize - Timbaland ft. OneRepublic")
print("Big Big World – Emilia")
print("Count On Me – Bruno Mars")
print("Jingle Bells – James Lord Pierpont")
print("Lemon Tree – Fool’s Garden")
print("Let her go – Passenger")
print("Love Paradise – Kelly Chan")
print("One Day – Charice")