print("Về nhà đi con")
print("Sống chung với mẹ chồng")
print("Người phán xử")
print("Quỳnh búp bê")
print("Gạo nếp gạo tẻ")
print("Mối tình đầu của tôi")
print("Tuổi thanh xuân")
print("Hoa hồng trên ngực trái")
print("Nàng dâu order")
print("Chạy trốn thanh xuân")