print("Đắc nhân tâm")
print("Cách nghĩ để thành công")
print("7 thói quen của người thành đạt")
print("Cuộc sống không giới hạn")
print("Hành trình về Phương Đông")
print("Người giàu có nhất thành Babylon")
print("Quẳng gánh lo đi mà vui sống")
print("Bộ sách – Hạt giống tâm hồn")
print("Tốc độ của niềm tin")
print("Thói quen thứ 8")